-- Your existing tables
CREATE TABLE IF NOT EXISTS top_stories (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS latest_news (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS videos (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS tv_channels (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS ticker (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS sports (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS weather_cities (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS election_states (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS election_config (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS election_visible (id INTEGER PRIMARY KEY CHECK (id = 1), value INTEGER);
CREATE TABLE IF NOT EXISTS no_election_message (id INTEGER PRIMARY KEY CHECK (id = 1), message TEXT);
CREATE TABLE IF NOT EXISTS footer_description (id INTEGER PRIMARY KEY CHECK (id = 1), description TEXT);
CREATE TABLE IF NOT EXISTS social_links (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);

-- NEW tables
CREATE TABLE IF NOT EXISTS market_data (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);
CREATE TABLE IF NOT EXISTS weather_data (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT);