name = "news-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "news_db"
database_id = "0e75dea9-e8e9-4d14-93b8-b156cc6f971f"

[vars]
ADMIN_SECRET = "your-very-strong-secret-key"